--Calculate the total revenue generated from all orders.
SELECT SUM(Sales) FROM sales;

--Find the average order value per customer.
SELECT Customer_Id, AVG(Sales)
FROM sales
GROUP BY Customer_Id;

--List the top 5 products with the highest total sales.
SELECT Product, sum(sales) total_sales
FROM sales
GROUP BY Product
ORDER BY total_sales DESC
LIMIT 5;

--Analyze the monthly revenue trend over time.
SELECT DATE_TRUNC('month', Order_Date) AS month,
       SUM(Sales) AS monthly_revenue
FROM sales
GROUP BY month
ORDER BY month;

--Determine the number of orders placed by each customer.
SELECT Customer_Id, COUNT(Order_Date) AS total_orders
FROM sales
GROUP BY Customer_Id;

--Compare the total revenue generated by each gender.
SELECT Gender, SUM(sales)
from sales
GROUP BY Gender


--Find the total sales for each product category and sort from highest to lowest.
SELECT Product_Category, SUM(Sales) AS total_sales
from sales
GROUP BY Product_Category
ORDER BY total_sales DESC

--Analyze how different discount levels affect the total sales.
select Discount, SAles(Sales) as total_sales
FROM sales
GROUP BY Discount


--Identify customers who have spent more than a specific threshold (500)
SELECT Customer_Id, SUM(Sales) AS total_spending
FROM sales
GROUP BY Customer_Id
HAVING SUM(Sales) >= 500

--Calculate the average shipping cost per order.
SELECT AVG(Shipping_Cost) as avg_shipping_cost
FROM sales


